### ISSUE TITLE
[TASK] absolute paths & user spec.

### ISSUE THREAD

**Issue by xerc** [passbolt/passbolt_help#101]
https://github.com/search?q=repo%3Apassbolt%2Fpassbolt_help%20%2Fusr%2Fshare%2Fphp%2Fpassbolt&type=code

ref. https://help.passbolt.com/hosting/update/source.html
`$ sudo -H -u www-data bash -c "./bin/cake passbolt migrate --backup"`
`$ sudo -H -u www-data bash -c "./bin/cake cache clear_all"`
`$ sudo -H -u  bash -c "/usr/share/php/passbolt/bin/cake passbolt healthcheck"` << ?!

**Comment by qntoni** [comment]
Hello @xerc,
Thanks for taking the time to open an issue.

Actually, when it comes to the package installation the correct absolute path is /usr/share/php/passbolt/bin/cake so there is no changes needed. When it comes to the from source comparison, users have manually moved to /var/www/passbolt using the `cd` command. That's why we are not using the absolute path there.

Best regards

**Comment by qntoni** [comment]
Hello @xerc,
Thanks for pointing that out.

I have created an internal ticket for this issue (ref. PB-28120) it should be fixed soon.

Best regards

**Comment by qntoni** [comment]
Hello @xerc,
The update has been merged on the help site.

Thanks for your help!

Best regards.

**Comment by xerc** [comment]
thx // ref. https://github.com/passbolt/passbolt_help/commit/c047371af579ae444d98450affe7e8e418e43cef
