### ISSUE TITLE
Improvement suggestions for SLES setup instructions

### ISSUE THREAD

**Issue by dirkmueller** [passbolt/passbolt_help#108]
Following the instructions at https://passbolt.com/docs/hosting/install/ce/sles/ I have the following suggestions:

## avoid use of wget

wget is not a standard installed tool in the minimal system. you can achieve pretty much the same outcome by using `curl -O` instead, so 

```diff
-wget https://download.passbolt.com/ce/installer/passbolt-repo-setup.ce.sh
+curl -O https://download.passbolt.com/ce/installer/passbolt-repo-setup.ce.sh
```

then, the repo-setup script is using which(1) to determine whether zypper or other tools are available. which is sort of deprecated and might not be installed in really very minimal systems. There is an equivalent bash builtin, which would work the same way: 

```diff
--- passbolt-repo-setup.ce.sh-20240503  2024-05-03 11:46:47.838522592 +0000
+++ passbolt-repo-setup.ce.sh   2024-05-03 11:49:06.370671699 +0000
@@ -141,13 +141,13 @@
       then
           CODENAME="focal"
       fi
-  elif which zypper > /dev/null 2>&1
+  elif test -e "$(type -p zypper)" > /dev/null 2>&1
   then
       PACKAGE_MANAGER=zypper
-  elif which dnf > /dev/null 2>&1
+  elif test -e "$(type -p dnf)" > /dev/null 2>&1
   then
       PACKAGE_MANAGER=dnf
-  elif which yum > /dev/null 2>&1
+  elif test -e "$(type -p yum)" > /dev/null 2>&1
   then
       PACKAGE_MANAGER=yum
   else
@@ -349,4 +349,4 @@
```

**Comment by qntoni** [comment]
Hello @dirkmueller,
Thanks a lot for your feedback, we really appreciate the time you've taken to help us.

Regarding `curl` instead of `wget`, we chose to use `curl -LO` to make curl follow HTTPS redirects, which is crucial when the target file has been moved to a different location. This is especially important when performing operations like SHA checksum verification, as the correct file must be retrieved for accurate validation. (ref. [PB-33239](https://github.com/passbolt/passbolt-docs/commit/2713f8f37d362bbed8bb0c7ebb73d425344bb1d4))

With the repo setup script, we chose to use `command -v` over `test -e` for checking command availability because `command -v` is more versatile in verifying all executable types the shell can run, including built-ins, functions, and aliases—not merely executables in the PATH. This ensures a thorough check for command presence. Additionally, using `command -v` avoids issues like [ShellCheck's SC2065 warning](https://github.com/koalaman/shellcheck/wiki/SC2065), which flags the misuse of redirections in conditional tests where a command check is intended. (ref [PB-33238](https://github.com/passbolt/passbolt-dep-scripts/commit/e74a2f9d6f319bdd796107211f80dd53ded579e1))

Thanks again.

Best regards,
Antony
