### ISSUE TITLE
Questions about deploy, backup, restore and redeploy

### ISSUE THREAD

**Issue by europ** [passbolt/passbolt_help#18]
Could you, please, add the following missing things:
* Ansible role to automate the deployment of the passbolt
* backup script or an Ansible role to create a backup
    * backup restoring may be also included
* documentation related to restoring a backup

In [this](https://community.passbolt.com/t/multiple-questions-about-existing-and-future-process-to-backup-redeploy-restore-a-passbolt-server/107/2) article (November 2017) @stripthis metioned that some of the items above will be added. I still could not find any of those. Are they going to be added as it was planned or the request was already canceled?

> enough users show interest

I think, that many of users are truly interested. :slightly_smiling_face:

**Comment by AnatomicJC** [comment]
Hi @europ,

Some topics have been done:

* Backup how-to is described here: https://help.passbolt.com/hosting/backup
* You have [https://help.passbolt.com/hosting/upgrade](on this page) some topics about how to migrate to a new OS and restoring from backup
* We also have released since this request deb and rpm native packages: https://help.passbolt.com/hosting/install

We don't have any official ansible playbook for now, only community contributions:
* ansible setup for passbolt on docker with backup scripts included: https://github.com/neuroforgede/passbolt_ansible
* passbolt setup bash script using official deb/rpm packages: https://gitlab.com/AnatomicJC/passbolt-setup

I will close this issue for now, feel free to open a new thread on our [community forum](https://community.passbolt.com/) if you still have other requests.

Best regards,
